### ISSUE TITLE
Define the API

### ISSUE THREAD

**Issue by NickNaso** [mauro-d/keep-or-skip#1]
Please specify the API of the module so we can start to work at unit tests and some internal improvements. For the rest the code seems to be good. We need to start using CI to automate the execution of unit tests.

**Comment by mauro-d** [comment]
The API is described in [this](https://github.com/mauro-d/keep-or-skip#type-signature) section of the documentation. If the API specification are ok for you and you don't have any other tip or suggestion, then we can close this issue.

**Comment by NickNaso** [comment]
It seems good for me. I provide to close the issue.
